--- 
 - name: Ensure that git is installed
   package: 
     name: git

 - name: Clone osm2shp git repo
   git: 
     repo: "{{ osm2shp_git }}" 
     dest: "{{ osm2shp_dir }}" 
     force: true
   notify: recompile-osm2shp
   ignore_errors: true

 - name: install osmium and osm tools
   package:
     name: "{{ item }}"
   with_items:
     - osmium-tool
     - osmctools   
      

 - name: install compile dependencies
   package: 
     name: "{{ item }}"
   with_items: 
     - gcc
     - g++
     - libshp-dev
     - libsqlite3-dev
     - libboost-iostreams-dev
     - libexpat1-dev
     - zlib1g-dev
     - make
     - libosmpbf-dev
   notify: recompile-osm2shp

 - name: install runtime dependencies
   package: 
     name: "{{ item }}"
   with_items: 
     - grass
