--- 
 - name: add backports repo to jessie
   apt_repository: repo={{ debian_jessie_backports }} 

 - name: Ensure that git is installed
   apt: name=git

 - name: Clone osm2shp git repo
   git: repo={{ osm2shp_git }} dest={{ osm2shp_dir }}
   notify: recompile-osm2shp
   ignore_errors: true

 - name: install compile dependencies
   apt: name={{ item }}
   with_items: 
     - gcc
     - g++
     - libshp-dev
     - libsqlite3-dev
     - libboost-iostreams-dev
     - libexpat1-dev
     - zlib1g-dev
     - make
     - libosmium-dev
   notify: recompile-osm2shp

 - name: install runtime dependencies
   apt: name={{ item }}
   with_items: 
   - grass
